### ISSUE TITLE
Validator fails for single value for arrays

### ISSUE THREAD

**Issue by yetithefoot** [BiteBit/koa-oai-router#41]
I specified array parmeter as multi string:

```yaml
        - in: query
          name: keywords 
          type: array
          collectionFormat: multi
          items:
            type: string
```

but when just single value is passed
```bash 
curl localhost:3035/endpoint?keywords=mykeyword"
```

it fails with error

```json
{
    "detail": {
        "dataPath": ".keywords",
        "keyword": "type",
        "message": "should be array",
        "params": {
            "type": "array"
        },
        "schemaPath": "#/properties/keywords/type"
    },
    "error": "should be array",
    "path": ".keywords",
    "status": 400,
    "type": "query"
}
```
